from typing import Any, Dict, Optional, Union, overload

from playwright.sync_api import (
    Browser,
    BrowserContext,
    Playwright,
    PlaywrightContextManager,
)
from typing_extensions import Literal

from camoufox.virtdisplay import VirtualDisplay

from .utils import launch_options, sync_attach_vd
from ._tzhelper import config_color_scheme as _config_color_scheme
from ._tzhelper import config_timezone as _config_timezone


def _context_defaults(from_options: Optional[Dict[str, Any]]) -> Dict[str, Any]:
    """Identity values that only apply if forwarded as context options."""
    defaults: Dict[str, Any] = {}
    tz = _config_timezone(from_options)
    if tz:
        defaults["timezone_id"] = tz
    scheme = _config_color_scheme(from_options)
    if scheme:
        defaults["color_scheme"] = scheme
    return defaults


def _inject_context_defaults(browser: Browser, defaults: Dict[str, Any]) -> None:
    """Apply those defaults to implicitly-created contexts.

    A plain launch() returns a Browser whose new_page()/new_context() build
    fresh contexts; wrap them so each value is supplied unless the caller
    passed one of their own.
    """
    orig_new_page = browser.new_page
    orig_new_context = browser.new_context

    def new_page(**kwargs: Any) -> Any:
        for key, value in defaults.items():
            kwargs.setdefault(key, value)
        return orig_new_page(**kwargs)

    def new_context(**kwargs: Any) -> Any:
        for key, value in defaults.items():
            kwargs.setdefault(key, value)
        return orig_new_context(**kwargs)

    browser.new_page = new_page  # type: ignore[method-assign]
    browser.new_context = new_context  # type: ignore[method-assign]


class Camoufox(PlaywrightContextManager):
    """
    Wrapper around playwright.sync_api.PlaywrightContextManager that automatically
    launches a browser and closes it when the context manager is exited.
    """

    def __init__(self, **launch_options):
        super().__init__()
        self.launch_options = launch_options
        self.browser: Optional[Union[Browser, BrowserContext]] = None

    def __enter__(self) -> Union[Browser, BrowserContext]:
        super().__enter__()
        self.browser = NewBrowser(self._playwright, **self.launch_options)
        return self.browser

    def __exit__(self, *args: Any):
        if self.browser:
            self.browser.close()
        super().__exit__(*args)


@overload
def NewBrowser(
    playwright: Playwright,
    *,
    from_options: Optional[Dict[str, Any]] = None,
    persistent_context: Literal[False] = False,
    **kwargs,
) -> Browser: ...


@overload
def NewBrowser(
    playwright: Playwright,
    *,
    from_options: Optional[Dict[str, Any]] = None,
    persistent_context: Literal[True],
    **kwargs,
) -> BrowserContext: ...


def NewBrowser(
    playwright: Playwright,
    *,
    headless: Optional[Union[bool, Literal['virtual']]] = None,
    from_options: Optional[Dict[str, Any]] = None,
    persistent_context: bool = False,
    debug: Optional[bool] = None,
    **kwargs,
) -> Union[Browser, BrowserContext]:
    """
    Launches a new browser instance for Camoufox given a set of launch options.

    Parameters:
        from_options (Dict[str, Any]):
            A set of launch options generated by `launch_options()` to use
        persistent_context (bool):
            Whether to use a persistent context.
        **kwargs:
            All other keyword arugments passed to `launch_options()`.
    """
    if headless == 'virtual':
        virtual_display = VirtualDisplay(debug=debug)
        kwargs['virtual_display'] = virtual_display.get()
        headless = False
    else:
        virtual_display = None

    try:
        if from_options is None:
            from_options = launch_options(headless=headless, debug=debug, **kwargs)

        # Forward identity values that only take effect as context options:
        # the timezone (the MaskConfig-only per-realm override can leak the
        # host tz through the window-creation path) and prefers-color-scheme
        # (no other path moves it — see _tzhelper.config_color_scheme).
        defaults = _context_defaults(from_options)

        # Persistent context
        if persistent_context:
            for key, value in defaults.items():
                from_options.setdefault(key, value)
            context = playwright.firefox.launch_persistent_context(**from_options)
            return sync_attach_vd(context, virtual_display)

        # Browser
        browser = playwright.firefox.launch(**from_options)
        if defaults:
            _inject_context_defaults(browser, defaults)
        return sync_attach_vd(browser, virtual_display)
    except Exception:
        if virtual_display:
            virtual_display.kill()
        raise
