from typing import Any, Dict, Optional, Union, overload

from playwright.sync_api import (
    Browser,
    BrowserContext,
    Playwright,
    PlaywrightContextManager,
)
from typing_extensions import Literal

from camoufox.virtdisplay import VirtualDisplay

from .utils import launch_options, sync_attach_vd
from ._tzhelper import config_timezone as _config_timezone


def _inject_context_timezone(browser: Browser, tz: str) -> None:
    """Default the timezone of implicitly-created contexts to the spoofed tz.

    A plain launch() returns a Browser whose new_page()/new_context() build
    fresh contexts; wrap them so `timezone_id` is supplied unless the caller
    passed one of their own.
    """
    orig_new_page = browser.new_page
    orig_new_context = browser.new_context

    def new_page(**kwargs: Any) -> Any:
        kwargs.setdefault("timezone_id", tz)
        return orig_new_page(**kwargs)

    def new_context(**kwargs: Any) -> Any:
        kwargs.setdefault("timezone_id", tz)
        return orig_new_context(**kwargs)

    browser.new_page = new_page  # type: ignore[method-assign]
    browser.new_context = new_context  # type: ignore[method-assign]


class Camoufox(PlaywrightContextManager):
    """
    Wrapper around playwright.sync_api.PlaywrightContextManager that automatically
    launches a browser and closes it when the context manager is exited.
    """

    def __init__(self, **launch_options):
        super().__init__()
        self.launch_options = launch_options
        self.browser: Optional[Union[Browser, BrowserContext]] = None

    def __enter__(self) -> Union[Browser, BrowserContext]:
        super().__enter__()
        self.browser = NewBrowser(self._playwright, **self.launch_options)
        return self.browser

    def __exit__(self, *args: Any):
        if self.browser:
            self.browser.close()
        super().__exit__(*args)


@overload
def NewBrowser(
    playwright: Playwright,
    *,
    from_options: Optional[Dict[str, Any]] = None,
    persistent_context: Literal[False] = False,
    **kwargs,
) -> Browser: ...


@overload
def NewBrowser(
    playwright: Playwright,
    *,
    from_options: Optional[Dict[str, Any]] = None,
    persistent_context: Literal[True],
    **kwargs,
) -> BrowserContext: ...


def NewBrowser(
    playwright: Playwright,
    *,
    headless: Optional[Union[bool, Literal['virtual']]] = None,
    from_options: Optional[Dict[str, Any]] = None,
    persistent_context: bool = False,
    debug: Optional[bool] = None,
    **kwargs,
) -> Union[Browser, BrowserContext]:
    """
    Launches a new browser instance for Camoufox given a set of launch options.

    Parameters:
        from_options (Dict[str, Any]):
            A set of launch options generated by `launch_options()` to use
        persistent_context (bool):
            Whether to use a persistent context.
        **kwargs:
            All other keyword arugments passed to `launch_options()`.
    """
    if headless == 'virtual':
        virtual_display = VirtualDisplay(debug=debug)
        kwargs['virtual_display'] = virtual_display.get()
        headless = False
    else:
        virtual_display = None

    try:
        if from_options is None:
            from_options = launch_options(headless=headless, debug=debug, **kwargs)

        # Forward the spoofed timezone to the Playwright context so the juggler
        # applies it reliably (the MaskConfig-only per-realm override can leak
        # the host tz through the window-creation path).
        tz = _config_timezone(from_options)

        # Persistent context
        if persistent_context:
            if tz:
                from_options.setdefault("timezone_id", tz)
            context = playwright.firefox.launch_persistent_context(**from_options)
            return sync_attach_vd(context, virtual_display)

        # Browser
        browser = playwright.firefox.launch(**from_options)
        if tz:
            _inject_context_timezone(browser, tz)
        return sync_attach_vd(browser, virtual_display)
    except Exception:
        if virtual_display:
            virtual_display.kill()
        raise
